### ISSUE TITLE
[Feature Request] Support  multiple languages in comments

### ISSUE THREAD

**Issue by WGB5445** [move-language/move#1038]
# 🚀 Feature Request

## Motivation

When writing code, you may write comments in multiple languages.
but it is not supported in Move files, which is very inconvenient

## Pitch

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
yes

**Comment by zsluedem** [comment]
https://github.com/move-language/move/issues/262#issuecomment-1190378746 for your reference
