### ISSUE TITLE
[Bug] A patch for a DoS vulnerability needs to be applied

### ISSUE THREAD

**Issue by poetyellow** [move-language/move#1059]
There is a critical Move VM vulnerability that has been fixed by Sui move and Aptos move, but this project has not fix that vulnerability. 

In addition to Sui and Aptos, some blockchains are also using the Move virtual machine.

Sui move patch link
	https://github.com/MystenLabs/sui/commit/8b681515c0cf435df2a54198a28ab4ef574d202b

Aptos move patch link
	https://github.com/aptos-labs/aptos-core/commit/47a0391c612407fe0b1051ef658a29e35d986963

credit : poetyellow from **Beosin**

**Comment by tzakian** [comment]
Thanks for the report @poetyellow! Patch has been landed so closing this out.
