### ISSUE TITLE
Can not compile basic example 

### ISSUE THREAD

**Issue by ikhana** [move-language/move#1061]
newbie here and when I try to tun the basic example here 

https://diem.github.io/move/creating-coins.html

I face this issue 

C:\Users\Inaam\toycoin>movecli sandbox publish src/modules
error[E01001]: invalid character
  ┌─ src/modules\coin.move:1:14
  │
1 │ address 0x2 {

**Comment by wrwg** [comment]
This is the wrong repo to ask these question. This repo is only for developers of Move itself. Please head over to either Aptos or Sui and ask on there user forums, there will be a lot of people able to help.
