### ISSUE TITLE
Update rust-toolchain.toml to latest version

### ISSUE THREAD

**Issue by FriendlyLifeguard** [move-language/move#1076]
While following the move tutorial in the aptos-core repo: 
https://github.com/aptos-labs/move/blob/main/language/documentation/tutorial/README.md. 

I was not able to run 'cargo install --path language/tools/move-cli' due to outdated rustc version in the rust-toolchain.toml from the cloned repo: https://github.com/move-language/move.git. 

I was able to fix the issue by manually upgrading rustc and changing the version in the rust-toolchain.toml.

**Comment by wrwg** [comment]
These are the outdated resources you are using. The first link is to an outdated clone of the Move repo. For the 2nd link, the main branch of the move-language repo is rarely updated. You need to use the `--locked` argument to cargo to get it work. Better though, either use the Aptos Move tutorial or check out the Sui docs. Aptos is here: https://aptos.dev/move/book/SUMMARY. There you also find a link to the updated tutorial.
