### ISSUE TITLE
cargo install failed due to toml_edit version 

### ISSUE THREAD

**Issue by sglk123** [move-language/move#1077]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.com/invite/M95qX3KnG8)

root@vultr:/studyspace/move/move# cargo install --path language/tools/move-cli
  Installing move-cli v0.1.0 (/studyspace/move/move/language/tools/move-cli)
    Updating crates.io index
error: failed to compile `move-cli v0.1.0 (/studyspace/move/move/language/tools/move-cli)`, intermediate artifacts can be found at `/studyspace/move/move/target`

Caused by:
  package `toml_edit v0.19.15` cannot be built because it requires rustc 1.66.0 or newer, while the currently active rustc version is 1.65.0
  Either upgrade to rustc 1.66.0 or newer, or use
  cargo update -p toml_edit@0.19.15 --precise ver
  where `ver` is the latest version of `toml_edit` supporting rustc 1.65.0

how to solve this issue ?

**Comment by wrwg** [comment]
Please see #1076 for a solution.

**Comment by sglk123** [comment]
@wrwg hi, i have add cargo.lock for toml_edit v0.14.3 in move-cli project, but when i cargo install still got this issue, do u know how to fix it

**Comment by wrwg** [comment]
Do no add anything, just pass the option `--locked` to your cargo commands.
