### ISSUE TITLE
The sui-move-analyzer plug-in is installed in win10 vscode. Only code highlighting, no code error prompts. How to get code error prompts?

### ISSUE THREAD

**Issue by otctoken** [move-language/move#1094]
The sui-move-analyzer plug-in is installed in win10 vscode. Only code highlighting, no code error prompts. How to get code error prompts?

**Comment by alexanderludwig** [comment]
+1

**Comment by wrwg** [comment]
Please ask on Sui's discord. The move analyzer in this repo is not maintained. It has been forked and evolved elsewhere.
