### ISSUE TITLE
Error parsing '[package]' section of manifest, VSCode

### ISSUE THREAD

**Issue by kvitlich** [move-language/move#1097]
I installed the move-analyzer following official documentation https://marketplace.visualstudio.com/items?itemName=move.move-analyzer . For some reason when i open .move file it shows  Error parsing '[package]' section of manifest 
<img width="453" alt="image" src="https://github.com/move-language/move/assets/56553116/7678a8fb-3cab-404d-8192-d60156ff1d61"> 
Also, when i open .move file "go to the definition" , "Go References" and others features doesn't work, but seems like i have highlights.
<img width="640" alt="image" src="https://github.com/move-language/move/assets/56553116/53c904ba-5553-498b-9dfa-7fcba97dd099">
I tried to fix it about 3 days by deleting and installing all the packages. Please community, if someone had the same trouble or you know reasons why this happen i will be appreciate for any information!

**Comment by wrwg** [comment]
The Move analyzer in the Move repo here is not maintained. Rather you find an evolved and maintained analyzer by searching for it in VS Code.

**Comment by kvitlich** [comment]
> The Move analyzer in the Move repo here is not maintained. Rather you find an evolved and maintained analyzer by searching for it in VS Code.

What does mean "here"? In the VSCode or my project? The Move Analyzer actually links here

**Comment by wrwg** [comment]
Both the Aptos and Sui move analyzers have been forked from here and are currently maintained by Movebit. I don't know exactly where to find the Sui version, but the Aptos one is here: https://github.com/movebit/move/tree/aptos-move-analyzer. You need to search for "aptos move" or similar in VS (I'm not a VS user so I can't tell you how to exactly do this).

In general this is really not the right repo here for user question. You should ask on either the Aptos or the Sui discord channels.
