### ISSUE TITLE
[Feature Request]  Read the script signature in session 

### ISSUE THREAD

**Issue by areshand** [move-language/move#13]
# 🚀 Feature Request

## Motivation

To correctly execute a script, we need to have the signature of the script to (1) validate the script has the correct signature and (2) to determine how to add a signer into the args.

Now, there is already support for the script_function (some previous discussion happens here https://github.com/diem/move/issues/209). However, we still need a "load_script" function to provide similar functionalities.

**Comment by areshand** [comment]
Hi @tnowacki, didn't find there is support for load_script. do you plan to add util function to view the signature of script? cc: @zekun000  @msmouse

**Comment by tnowacki** [comment]
Ah yeah, can do. Should be easy to add

**Comment by areshand** [comment]
Hi @tnowacki when would you have time to make this change?

**Comment by tnowacki** [comment]
PR up
