### ISSUE TITLE
A suggestion for move tutorial

### ISSUE THREAD

**Issue by ShuaoZhang** [move-language/move#159]
## ❓ Questions and Help

As an amutar who recently started to learn Move language, I would like to have a suggestion on the official tutorial.

In the [step 2](https://github.com/move-language/move/blob/main/language/documentation/tutorial/README.md#step-2-adding-unit-tests-to-my-first-move-module), the tutorial doesn't mention we can only run `move package test` command after we build the package. This has caused me some confusion.

Thanks.

**Comment by jolestar** [comment]
Can you submit a pull request to improve it?

**Comment by ShuaoZhang** [comment]
#160

**Comment by tnowacki** [comment]
Closing this issue since, as indicated in #160, it is a bug
