### ISSUE TITLE
[Feature Request]Let Github support Move language

### ISSUE THREAD

**Issue by jolestar** [move-language/move#212]
# 🚀 Feature Request

## Motivation

Let Github support Move language, for syntax highlight and code lines statistic.

Need to create a PR to https://github.com/github/linguist

**Comment by sblackshear** [comment]
Hugely supportive of someone taking this on!

I think one of the preconditions for acceptance of such a PR is that there must be a certain number of repos on GitHub written in the language. I think https://www.movey.net/ may be able to help us with this (they seem to have a scheme for automatically finding and indexing Move packages on GitHub).

**Comment by uvd** [comment]
Hi, everyone
I'm  create a PR to https://github.com/github/linguist

https://github.com/github/linguist/pull/5955

move language label color  is  #4a137a  ,   have any better suggestions for this color

**Comment by geometryolife** [comment]
#535443

**Comment by jiangying000** [comment]
Found a way for showing colors in issue, replace `size`, `colorhex` with chosen value
`![](https://via.placeholder.com/[size]/[colorhex]/[colorhex].png)`

for example:
`![](https://via.placeholder.com/15/535443/535443.png)` for ![](https://via.placeholder.com/15/535443/535443.png)
`![](https://via.placeholder.com/15/4a137a/4a137a.png)` for ![](https://via.placeholder.com/15/4a137a/4a137a.png)


ref: https://github.com/github/markup/issues/1440#issuecomment-1148206907

**Comment by sblackshear** [comment]
I think we can close this now that https://github.com/github/linguist/pull/5955 has landed! Great work @uvd and @jolestar. 

> so, the Move brand color is blue?

Sorry for missing this before! This is indeed the logo, but there's no official brand color. I think the one @uvd selected is just fine (and not so far off the color of the tail in the Move logo).

Fun fact: the Move logo is inspired by the "lollipop" symbol from [linear logic](https://en.wikipedia.org/wiki/Linear_logic) (linear implication).
