### ISSUE TITLE
[Bug] Solidity tests don't work for me

### ISSUE THREAD

**Issue by gregnazario** [move-language/move#24]
# 🐛 Bug

Not sure I have the wrong version of the solidity compiler.  I installed it from node like this https://docs.soliditylang.org/en/v0.8.13/installing-solidity.html#npm-node-js

It's possible it requires a specific version, but just trying to make sure all the tests pass!

## To reproduce

**Code snippet to reproduce**
```rust
cargo test
```

**Stack trace/error message**
```
test run_all::dev_address/args.evm.txt ... FAILED
Error: Expected output differs from actual output:
Command `package build -v -d --arch ethereum`:
COMPILING A to Yul
GENERATING EVM bytecote from Yul
ERROR Failed to generate EVM bytecote
Error: error: unknown option '--strict-assembly'
```

## Expected Behavior

Working tests :)

## System information

**Please complete the following information:**
- Commit 2771ee6d9838fc17f437ba4f3aac48b407ca3f77
- Rust 1.60
- MacOS 12.3.1

**Comment by gregnazario** [comment]
Yeah, it was the latest when I ran it, I can try again

**Comment by wrwg** [comment]
Ah ok, You need to run `scripts/dev-setup.sh -dp` to get the right solidity compiler for local testing.

**Comment by vgao1996** [comment]
@gregnazario hope you were able to successfully figure out how to install the solidity dependencies!

What that being said, https://github.com/move-language/move/pull/57 just landed, which makes the solidity dependencies no longer a requirement if you don't care about them, so I'm closing this issue. Feel free to reopen if you have additional concerns!
