### ISSUE TITLE
[Bug] [move-cli] The move-cli package test --filter parameter does not take effect in some scenarios

### ISSUE THREAD

**Issue by yubing744** [move-language/move#254]
# 🐛 Bug

The move-cli package test --filter parameter does not take effect in some scenarios

## To reproduce

**Code snippet to reproduce**
```bash
git clone https://github.com/move-language/move.git
cd move/language/tools/move-cli/tests/move_unit_tests/assign_dev_addr_for_dep
move package test --filter M::nop
```

or 

```bash
git clone https://github.com/move-language/move.git
cd move/language/tools/move-cli/tests/move_unit_tests/assign_dev_addr_for_dep
move package test --filter 0x2::M::nop
```

## Expected Behavior

match one test

## System information

macOS: 10.14.6
move-cli: 0.1.0

## Additional context
move package help test:
-f, --filter <filter>
            A filter string to determine which unit tests to run. A unit test will be run only if it
            contains this string in its fully qualified (<addr>::<module_name>::<fn_name>) name

Code:  https://github.com/move-language/move/blob/7733658048a8bc80e9ba415b8c99aed9234eaa5f/language/tools/move-unit-test/src/test_runner.rs#L197

**Comment by yubing744** [comment]
@jolestar Can you help cherry pick this PR to starcoin and issue a new version?

**Comment by jiangying000** [comment]
with #337 `move test --filter` only matches module::test_fun, but not address, is this expected behaviour ?

**Comment by yubing744** [comment]
@jiangying000   I hope to solve this issue https://github.com/move-language/move/issues/271

**Comment by jiangying000** [comment]
Ok, it may take some time for #271 to be addressed, I can pick #337 to starcoinorg/move first

**Comment by yubing744** [comment]
@jiangying000 After repairing, cherry pick together.

**Comment by jiangying000** [comment]
> @jiangying000 After repairing, cherry pick together.

ok
