### ISSUE TITLE
[Bug] utf8 is not allowed

### ISSUE THREAD

**Issue by zsluedem** [move-language/move#262]
# 🐛 Bug

The compiler currently only accepts ASCII characters.

https://github.com/move-language/move/blob/a8383d88fa48f4e1e0e91264cffbbd27136e4732/language/move-compiler/src/parser/comments.rs#L15-L37

## To reproduce

**Code snippet to reproduce**
```rust
module 0xCAFE::BasicCoin {
    struct Coin has key {
        value: u64,
    }
    // 你好啊
    public fun mint(account: signer, value: u64) {
        move_to(&account, Coin { value })
    }
}
```

**Stack trace/error message**
```
error[E01001]: invalid character
  ┌─ ./sources/FirstModule.move:5:8
  │
5 │     // 你好啊
  │        ^^ Invalid character '你' found when reading file. Only ASCII printable characters, tabs (\t), lf (\n) and crlf (\r\n) are permitted.


```

## Expected Behavior

No compiler error should be showed.

## System information

**Please complete the following information:**
move-cli 0.1.0
rustc 1.60.0 (7737e0b5c 2022-04-04)
ubuntu18

Although the messages are not necessary.

## Additional context
No

**Comment by sblackshear** [comment]
We intentionally restrict comments to ASCII characters to prevent [trojan source](https://trojansource.codes/) vulnerabilities.
