### ISSUE TITLE
[Feature Request] Add a compile error if entry function returns any value.

### ISSUE THREAD

**Issue by JackyWYX** [move-language/move#286]
# 🚀 Feature Request

Add a compile error if entry function returns any value.

## Motivation

For aptos network, it is illegal to have the entry function return any values. E.g.

```
module Dev::HelloWorld {
    public(script) fun hello(): u64 { 5 }
}
```

```
$ aptos move run --function-id default::HelloWorld::hello
{
  "Error": "API error: transaction execution failed: Transaction Executed and Committed with Error INVALID_MAIN_FUNCTION_SIGNATURE"
}
```

This error can be reported at compile level. 

## Pitch

**Describe the solution you'd like**

Add a compile error when entry function returns some values. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Don't think I am capable of handle this error.

**Comment by wrwg** [comment]
The core Move language intentionally does not restrict input and output parameters of transactions. What is allowed here depends on the integration of Move. Errors should be reported on the Aptos compiler integration side. Please open this bug again in the [Aptos Repo](https://github.com/aptos-labs/aptos-core/issues).
