### ISSUE TITLE
[Feature Request] Add username to package_lock file

### ISSUE THREAD

**Issue by fardream** [move-language/move#346]
# 🚀 Feature Request

Add user name to the package lock file created by `language/tools/move-package/src/package_lock.rs`

## Motivation

We develop on a shared linux host. If one user creates the lock file (`language/tools/move-package/src/package_lock.rs`), no other user can lock the file and all builds fails.

## Pitch

If we can append user name to the package lock file (such as `/tmp/move_package_lock_{username}.lock`), different users will not impact each other's build.

(I can open a pr for this).

**Comment by sblackshear** [comment]
Good find! Adding the username makes sense + would gladly accept a PR for this.
