### ISSUE TITLE
How does move implement transferfrom in eth erc20?

### ISSUE THREAD

**Issue by greyireland** [move-language/move#394]
## ❓ Questions and Help
I can't transfer other people's resources. How can I transfer from?

**Comment by sblackshear** [comment]
This is not part of the core Move language. It is typically implemented via a standard like `Coin<T>` on the platform that uses Move. Here are some examples of fungible token implementations using these standards that might be helpful: https://github.com/MystenLabs/awesome-move#fungible-tokens
