### ISSUE TITLE
[Bug][move-prover] Prover behaves strangely with the while-loops

### ISSUE THREAD

**Issue by mkurnikov** [move-language/move#425]
# 🐛 Bug

It's reproducible with simple example:
```
module 0x1::math {
    public fun pow_10(degree: u8): u64 {
        let res = 1;
        let i = 0;
        while (i < degree) {
            res = res * 10;
            i = i + 1;
        };
        res
    }
}

spec 0x1::math {
    spec pow_10 {
        ensures degree == 0 ==> result == 1;
    }
}
```

and the stack trace is 
```
/home/mkurnikov/bin/aptos move prove
error: post-condition does not hold
   ┌─ /home/mkurnikov/code/prover-bugs/sources/math.move:15:9
   │
15 │         ensures degree == 0 ==> result == 1;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │
   =     at /home/mkurnikov/code/prover-bugs/sources/math.move:2: pow_10
   =         degree = 0u8
   =     at /home/mkurnikov/code/prover-bugs/sources/math.move:3: pow_10
   =         res = 1
   =     at /home/mkurnikov/code/prover-bugs/sources/math.move:4: pow_10
   =         i = 0u8
   =     at /home/mkurnikov/code/prover-bugs/sources/math.move:5: pow_10
   =     enter loop, variable(s) i, res havocked and reassigned
   =         i = 41u8
   =         res = 26502
   =     at /home/mkurnikov/code/prover-bugs/sources/math.move:9: pow_10
   =         result = 26502
   =     at /home/mkurnikov/code/prover-bugs/sources/math.move:15

FAILURE proving 1 modules from package `prover-bugs` in 1.198s
{
  "Error": "Move Prover failed: exiting with verification errors"
}
```

It seems that prover messes up variables in the loop, as the values in the stack trace really make no sense. 

## System information

**Please complete the following information:**
-  Latest Aptos at 9deb340d1e35ab5b2f46b9e984bceb1968d46243
-  Ubuntu 20.04

**Comment by junkil-park** [comment]
Hi Makxim, It seems that the verification has failed due to the lack of loop invariant, which is an expected result. Users currently need to provide [loop invariants](https://github.com/move-language/move/blob/main/language/move-prover/doc/user/spec-lang.md#loop-invariants) to verify loops. Here are some examples of loop invariants: https://github.com/move-language/move/blob/main/language/move-prover/tests/sources/functional/verify_vector.move

With loop macros (a new lang feature we're planning for the near future), writing loop invariants may be automated for certain types of loops, so that user don't need to provide any.

**Comment by junkil-park** [comment]
In this specific case, the loop invariant can be written as follows:
```
public fun pow_10(degree: u8): u64 {
    let res = 1;
    let i = 0;
    while ({
        spec {
            invariant res == spec_pow(10,i);
            invariant 0 <= i && i <= degree;
        };
        i < degree
    }) {
        res = res * 10;
        i = i + 1;
    };
    res
}

spec fun spec_pow(y:u64, x: u64): u64 {
    if (x == 0) {
        1
    }
    else {
        y * spec_pow(y, x-1)
    }
}

spec pow_10 {
    ensures degree == 0 ==> result == 1;
    ensures result == spec_pow(10, degree);
}
```

**Comment by junkil-park** [comment]
I will close this issue now, but please feel free to open another one if you have anything else.

**Comment by meng-xu-cs** [comment]
Impressive way of writing the loop invariant!

**Comment by wrwg** [comment]
Yes, recursive spec functions actually work quite well (made them work a while ago for the first macro experiments).
