### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by vgao1996** [move-language/move#439]
The IR compiler accepts the following invalid program (notice the `vec_push_back` is missing an argument):
```
main() {
    let i: u64;
    let v: vector<u64>;

label entry:
    i = 0;
label loop_start:
    jump_if_false (copy(i) < 1000) loop_end;

    v = vec_pack_0<u64>();
    _ = vec_len<u64>(&v);
    vec_push_back<u64>(0);
    _ = vec_imm_borrow<u64>(&v, 0);
    vec_swap<u64>(&mut v, 0, 0);
    _ = vec_pop_back<u64>(&mut v);
    vec_unpack_0<u64>(move(v));

    i = move(i) + 1;
    jump loop_start;
label loop_end:
    return;
}
```
This results in a NEGATIVE_STACK_SIZE_WITHIN_BLOCK error but it really should have been caught in an earlier stage.

**Comment by tnowacki** [comment]
This is the purpose of the IR, to let you test these items. So it is not a bug, it is a feature :)
