### ISSUE TITLE
[doc] address value '_' in move.toml  not explained in book

### ISSUE THREAD

**Issue by jiangying000** [move-language/move#463]
In book, https://move-language.github.io/move/packages.html the meaning of setting addr_name to **"_"** seems unexplained, I can not found out what's the meaning of `"std" = "_"` in move.toml

    [addresses]  # (Optional section) Declares named addresses in this package and instantiates named addresses in the package graph
    # One or more lines declaring named addresses in the following format
    <addr_name> = "_" | "<hex_address>" # e.g., std = "_" or my_addr = "0xC0FFEECAFE"
    
    [dev-addresses] # (Optional section) Same as [addresses] section, but only included in "dev" and "test" modes
    # One or more lines declaring dev named addresses in the following format
    <addr_name> = "_" | "<hex_address>" # e.g., std = "_" or my_addr = "0xC0FFEECAFE"

**Comment by sblackshear** [comment]
See https://move-language.github.io/move/packages.html#instantiation for an explanation. But improvements are welcome!

**Comment by jiangying000** [comment]
thanks, also find some related doc here, https://move-language.github.io/move/packages.html#instantiation:~:text=Declares%20named_addr%20as,an%20importing%20package.
