### ISSUE TITLE
[Feature Request] Move Package Caching updates local state

### ISSUE THREAD

**Issue by gregnazario** [move-language/move#468]
# 🚀 Feature Request

When I build a package, and it is using a git rev / branch, it should do a `git fetch & reset` to update the local cached git repository if you need updates.

## Motivation

It's a bad UX that the git repo never updates based on a branch.  Currently, people keep running into cache issues due to using branch names.

## Pitch

Right now users have to clear the cache, and it's not helpful

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by sblackshear** [comment]
Thanks for working on this @gregnazario? Can this issue be closed now?

**Comment by gregnazario** [comment]
Yes, now that it's finally not broken, I'll close it.
