### ISSUE TITLE
[Feature Request] in memory HashMap HashSet like data structures 

### ISSUE THREAD

**Issue by jiangying000** [move-language/move#475]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

 
in memory HashMap HashSet can be helpful in many cases for a O(1) look up, now I use std::vector to handle mapping requirements , but it might not that efficient when dataset is large

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
I am not able to do this right now

**Comment by jolestar** [comment]
if the dataset is large, we should use Table.

**Comment by sblackshear** [comment]
Yep, `Table` is the recommended approach here https://github.com/move-language/move/blob/main/language/extensions/move-table-extension/sources/Table.move

**Comment by jiangying000** [comment]
thanks, I would learn more about them
