### ISSUE TITLE
[Feature Request]i8,i32,i64,i128 for Negative Number and Log support

### ISSUE THREAD

**Issue by coolsnake** [move-language/move#551]
# 🚀 Feature Request

We have negative exponents and hope to call Log function to get the negative exponents vice verse. 

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by oxade** [comment]
We will not be supporting these any time soon.
But u16, u32, u256 are in [development](https://github.com/move-language/move/issues/453)

**Comment by sblackshear** [comment]
Would be very eager to learn more about your use-cases for these primitives.

Note that Movemate has some libraries for signed integers that may be helpful https://github.com/pentagonxyz/movemate/blob/main/sui/sources/i64.move

**Comment by coolsnake** [comment]
thanks

**Comment by coolsnake** [comment]
> Would be very eager to learn more about your use-cases for these primitives.
> 
> Note that Movemate has some libraries for signed integers that may be helpful https://github.com/pentagonxyz/movemate/blob/main/sui/sources/i64.move

Let say any price = 1.0001^N，here N can be Negative and Positive. N will be used in the swap algorithm.
