### ISSUE TITLE
[Feature Request] Simply abstract interpreter API's used in bytecode verifier 

### ISSUE THREAD

**Issue by sblackshear** [move-language/move#557]
The abstract interpreter's `analyze_function` returns an invariant map annotated with post-states or errors for each block. This is an overkill of information for the client, which only needs to know whether the analysis succeeded or failed (and with which error). We should refactor to get rid of "error postconditions", and simplify the return logic

See https://github.com/move-language/move/pull/556 for more context.

**Comment by tnowacki** [comment]
In terms of "simplification" I'm not sure if we have an issue for it, but we have discussed removing the abstract interpreter from the bytecode verifier. Where instead we just check provided annotations for the initial states of blocks (we technically only need it for loop heads, but... thats its own discussion).

I know simplifying the API is maybe nice without these other changes. Just thought it is worth mentioning somewhere, when discussing the simplifications we can do.

**Comment by sblackshear** [comment]
It will take awhile to figure this out, but definitely worth looking into this as part of our longer-term plans. I'd be in favor of moving ahead with the simplications in the meantime (I think we're looking at ~1-2 PR's for that)

**Comment by wrwg** [comment]
I just can say *super* careful making changes to the verifier. Best *don't* make any changes if it works (and is not a user facing surface you'd like to improve, or something terrible inefficient). Removing absint is something which Aptos would most likely oppose.
