### ISSUE TITLE
[Bug] Move Prover panicks during borrow analysis

### ISSUE THREAD

**Issue by martin-neuhaeusser** [move-language/move#648]
# 🐛 Bug
The example Move project in [merge_sort.zip](https://github.com/move-language/move/files/9945968/merge_sort.zip) implements merge sort on `vector<u64>`. It compiles without issues (using move commit  3174338) and a simple test succeeds. The code does not contain any specifications apart from a `pragma opaque` which is required for a recursive function.
Still, the Move Prover panicks during model construction:
![image](https://user-images.githubusercontent.com/11831771/200174587-2d65e097-987c-425e-8a48-bcc3f8c87048.png)

**Comment by rahxephon89** [comment]
Here is a simplified example:
```
address merge_sort {
    module m {
        public fun foo_1() {
            foo_2();
        }
        fun foo_2() {
            foo_2();
           foo_3();
        }
        fun foo_3() {
        }
    }
}
```

**Comment by wrwg** [comment]
Is this really done? We removed the crash, but still want borrow analysis of the prover work with recursive functions.

**Comment by rahxephon89** [comment]
> 

The landed PR works for the merge sort example but it does not work for mutual recursion

**Comment by rahxephon89** [comment]
Issue #667 with a more specific example is opened so closed this one
