### ISSUE TITLE
[Bug] New integer types (`u16`, `u32`, `u256`) cannot be passed as type arguments to the Move CLI

### ISSUE THREAD

**Issue by sblackshear** [move-language/move#650]
# 🐛 Bug

The type tag parser in the Move CLI does not understand the new integer types `u16`, `u32`, `u256`

## To reproduce

`move sandbox run script.move --type-args u16`

Note: relevant code to fix is here https://github.com/move-language/move/blob/main/language/move-core/types/src/parser.rs#L270

**Comment by oxade** [comment]
Thanks for flagging @sblackshear 
Fix is here https://github.com/move-language/move/pull/651
