### ISSUE TITLE
[Prover] Not yet supported constant vector type: Vector(Primitive(Bool))

### ISSUE THREAD

**Issue by awelc** [move-language/move#653]
# 🐛 Bug

The Move Prover not yet supports constant bool vectors.

Happy to dig into it myself but tagging @rahxephon89 as he expressed interest in providing feedback.

## To reproduce

Run prover on the following module:
```
module bool_vec::bool_vec {
    fun foo(): vector<bool> {
        let v = vector[];
        v
    }
}
```

**Stack trace/error message**

```
thread 'main' panicked at 'not implemented: Not yet supported constant vector type: Vector(Primitive(Bool))', language/move-prover/bytecode/src/stackless_bytecode_generator.rs:1348:22
```

## Expected Behavior

This piece of code should verify correctly.

## System information

Main branch of the Move repo (sha: 3ac0cd7b78cc2a6d470b7fefbfd82b0c044ef576) built on a Mac.

**Comment by rahxephon89** [comment]
According to [here](https://github.com/move-language/move/pull/411), we may want a general method instead of adding a special case for bool. @meng-xu-cs @wrwg @junkil-park

**Comment by junkil-park** [comment]
Yes, Prover needs to support vector constants for all types. I added the special support of address arrays in order to unblock our specification ASAP a few month ago. I will include this work item in our task list.

**Comment by awelc** [comment]
@junkil-park - may I ask what the timeline for this would be? It's one of the blockers for us at this point... Again, I am happy to give it a try myself, particularly if the timeline is long-ish. It would help if someone could provide some (high-level?) suggestions for this beyond using ` Vector(Vec<Value>)` to generalize support for vectors.

**Comment by rahxephon89** [comment]
> 

I am working on it. I hope I can get something done this week
