### ISSUE TITLE
[Prover] timeouts for the aborts_if condition with `type_info::type_name`

### ISSUE THREAD

**Issue by junkil-park** [move-language/move#702]
## How to reproduce
Remove this line https://github.com/aptos-labs/aptos-core/pull/5712/files#diff-ea654812ad5dedf593924a939254fe4c38db4eb93144ad74c7b0f85882052be6R19.

Run Prover, and it will timeout.

## Expected output
Prover doesn't timeout.

**Comment by meng-xu-cs** [comment]
I am not seeing a timeout when I try to reproduce this issue, @junkil-park would you mind giving it another try with the latest prover on the `main` branch?

FYI: the command I used to reproduce is:
(assuming `move-stdlib` and `aptos-stdlib` reside in where they should be)

```bash
	cargo run -- \
		-d move-stdlib/sources \
		-a std=0x1 \
		-a aptos_std=0x1 \
		-a aptos_framework=0x1 \
		-a aptos_token=0x1 \
		-a core_resources=0xA550C18 \
		-a vm_reserved=0x0 \
		-a Extensions=0x1 \
		--dump-bytecode \
		aptos-stdlib/sources
```

**Comment by junkil-park** [comment]
This has been resolved.
