### ISSUE TITLE
[Feature Request] Index based insertion of vector items

### ISSUE THREAD

**Issue by nilz3ro** [move-language/move#766]
# 🚀 Feature Request

It would be helpful to have control of the precise index in which an item is inserted into a vector.
Currently the `vector::push_back` function is used to append items to a vector, but there is no way to insert an item at a specific index. 

## Motivation

If someone wanted to build an vector-backed binary search tree, or some other type backed by a vector, they would need to carefully control the index where items are inserted. Another hypothetical case would be when someone wants to remove an item from a vector at a given index, and later insert a new object at the index where the previous item was removed.

## Pitch

The pitch is to add a `vector::insert<T>(self: &mut Vector, item: T, index: u64)` function, or a similar function that allows the caller to specify an index.

**Comment by sblackshear** [comment]
By a stroke of luck, I just needed this in some Sui code I was writing yesterday--will put up a PR. It makes sense to have this given that we have `remove` and the implementation is very similar.

**Comment by nilz3ro** [comment]
@sblackshear would it be possible to add slices to Sui Move? It could just be a function that lets you get a (mutable) ref to a range of elements in an array.

**Comment by PaulFidika** [comment]
Slice would be great to have as well! I ran into a need for it so I wrote up a function for it and put it in our Sui Utils repo:

https://github.com/0xcapsules/sui-utils/blob/master/package/sources/vector.move

But I think it should be built into std::vector itself.

**Comment by sblackshear** [comment]
@nilz3ro @PaulFidika feel free to open a separate issue and/or PR for the slice functionality! Agreed that this would be useful.

Closing this issue given that we now have `insert`.
