### ISSUE TITLE
[Bug][move-analyzer] error parsing address on a dependant Move.toml

### ISSUE THREAD

**Issue by kklas** [move-language/move#801]
# 🐛 Bug

I have a following section in Move.toml for a **Sui** smart contract

```
[package]
name = "amm"
version = "0.1.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet-0.20.0" }

[addresses]
amm = "0x9d73f238af913517470f1b2cf01a7eea649ee3e9"
```

I am then then importing this package in another package by specifying `amm = { ... }` in the `[dependencies]` seciton.

Move Language Server is then throwing the following error in VS Code:

```
symbolication failed: Error parsing '[addresses]' section of manifest

Caused by:
    0: Invalid address '0x9d73f238af913517470f1b2cf01a7eea649ee3e9' encountered.
    1: Unable to parse AccountAddress (must be hex string of length 16)
```

The address is valid (I've double checked on the explorer) and both packages otherwise compile fine. The problem is just with move analyzer.

I'm using the latest version of move-analyzer installed today with `cargo install --git https://github.com/move-language/move move-analyzer`

**Comment by sblackshear** [comment]
`cargo install --git https://github.com/move-language/move move-analyzer --features "address20"` should hopefully fix the issue

**Comment by kklas** [comment]
Ah I've missed this piece of doc. It works now. Thanks!
