### ISSUE TITLE
[move] Missing Boogie implementation of `type::name_get` function from stdlib

### ISSUE THREAD

**Issue by awelc** [move-language/move#803]
# 🐛 Bug

When adding a new native function in the `type` stdlib module (sha: https://github.com/move-language/move/commit/e9b0aeda778c1c46bd12eefaafdad7be3dd93209), the equivalent Boogie implementation has not been added.

Assigning myself to this issue but also @sblackshear in case he has an immediate idea what the Boogie side of things should look like.

**Comment by awelc** [comment]
Also added @meng-xu-cs in case he has some feedback or advice.

**Comment by zengxinhai** [comment]
I have some use cases for the type_name::get. I think it's a very powerful syntax.
## Background 
I'm building a lending platform. So it's necessary to manage a portfolio of user's assets and debts.
And the types of assets and debts will be different for each user.

## User cases
Each time a user interact with the modules, I need to calculate the interests for all his/her debts. So I need to store what types of debts the user has. For example, Alice may have borrowed SUI, BTC,  Bob may have borrowed ETH, USDC. So I add a vector for their position to store those debt types for them. And I would do something like this:
```move
  public(friend) fun accrue_interests(
    position: &mut Position,
    bank: &Bank,
  ) {
    let debtTypes = debt_types(position);
    let (i, n) = (0, vector::length(&debtTypes));
    while (i < n) {
      let type = *vector::borrow(&debtTypes, i);
      let newBorrowIndex = bank::borrow_index(bank, type);
      position_debts::accure_interest(&mut position.debts, type, newBorrowIndex);
      i = i + 1;
    };
  }
```

To store the user's collaterals, I made a bag to store any kinds of coins. I
## BalanceBag
```move
/**
In some cases, the app need to manage balances for different tokens in one place.
This module is created for this purpose.

It supports:
1. Put any type of balance into the bag
2. Retrieve, update the balances in the bag
*/
module x::balance_bag {
  use std::type_name::{Self, TypeName};
  use sui::bag::{Self, Bag};
  use sui::balance::{Self, Balance};
  use sui::object::{Self, UID};
  use sui::tx_context;
  
  struct BalanceBag has store {
    id: UID,
    bag: Bag,
  }
  
  public fun new(ctx: &mut tx_context::TxContext): BalanceBag {
    BalanceBag {
      id: object::new(ctx),
      bag: bag::new(ctx),
    }
  }
  
  public fun init_balance<T>(self: &mut BalanceBag) {
    let typeName = type_name::get<T>();
    bag::add(&mut self.bag, typeName, balance::zero<T>())
  }
  
  public fun join<T>(self: &mut BalanceBag, balance: Balance<T>) {
    let typeName = type_name::get<T>();
    let inBagBalance = bag::borrow_mut<TypeName, Balance<T>>(&mut self.bag, typeName);
    balance::join(inBagBalance, balance);
  }
  
  public fun split<T>(self: &mut BalanceBag, amount: u64): Balance<T> {
    let typeName = type_name::get<T>();
    let inBagBalance = bag::borrow_mut<TypeName, Balance<T>>(&mut self.bag, typeName);
    balance::split(inBagBalance, amount)
  }
  
  public fun value<T>(self: &BalanceBag): u64 {
    let typeName = type_name::get<T>();
    let inBagBalance = bag::borrow<TypeName, Balance<T>>(&self.bag, typeName);
    balance::value(inBagBalance)
  }
  
  public fun contains<T>(self: &BalanceBag): bool {
    let typeName = type_name::get<T>();
    bag::contains_with_type<TypeName, Balance<T>>(&self.bag, typeName)
  }
  
  public fun bag(self: &BalanceBag): &Bag {
    &self.bag
  }
  
  public fun destroy_empty(self: BalanceBag) {
    let BalanceBag { id, bag } = self;
    object::delete(id);
    bag::destroy_empty(bag);
  }
}
```

**Comment by meng-xu-cs** [comment]
As far as I can tell, the prover is already able to handle it (or sth very similar).

I'll suggest to trace the code from here: https://github.com/move-language/move/blob/main/language/move-model/src/well_known.rs#L13-L14

You might want to add two additional *well-known* functions, `type_name::get` and `type_name::$get` and make them behave similarly to existing `TYPE_NAME_MOVE` and `TYPE_NAME_SPEC`

**Comment by awelc** [comment]
I looked into it and I have to say it beats me on how to support it... Here are some comments, hopefully @meng-xu-cs and/or @sblackshear can provide additional feedback and/or advice.

As I understand it, the model for the `type_name::get` native function should produce the same result as the native function itself, that is a string representing the type.

Unfortunately, in the implementation of `type_name::get` function this string is computed on `TypeTag` which and the only "thing" that is available in the Prover is `Type` and it's not even `runtime_types::Type` but `ty::Type` from the move model.

The most straightforward idea then, which is to re-use the type-to-string conversion defined on `TypeTag` in the Prover is not easily done as there is no easy way to translate `ty::Type` to `TypeTag`.

It may still be possible using some functionality in the `interpreter` crate - it has some conversion functions that may work here:
- [convert_model_base_type](https://github.com/move-language/move/blob/469a6be033b394c8281305fc74879b14360c652c/language/move-prover/interpreter/src/concrete/ty.rs#L805) to convert move-model's `ty::Type` to interpreter's own `BaseType`
- [to_move_type_tag](https://github.com/move-language/move/blob/469a6be033b394c8281305fc74879b14360c652c/language/move-prover/interpreter/src/concrete/ty.rs#L452) to convert `BaseType` to `TypeTag`

The interpreter, though, seems even more experimental than the Prover core and I wonder if it even makes sense to rely on its code for this (and if what I am proposing seems feasible at least on the surface).

Hopefully @meng-xu-cs can comment on that and, alternatively, perhaps @sblackshear has some alternative ideas on how to handle this.

**Comment by zengxinhai** [comment]
Any progress on this? Move prover is critical for the safety of code
