### ISSUE TITLE
[Bug] public Inline functions accessing local struct is not usable by other modules

### ISSUE THREAD

**Issue by lightmark** [move-language/move#959]
# 🐛 Bug

if module `x` defined a struct `A` and `public inline func b()` and `b` access `A`'s internal field. Then any callsite outside `x` cannot use `b` since when `b` is expanded at the callsite, accessing `A`'s fields becomes a violation.

## Expected Behavior

any callside other than `x` and call `b` w/o any issue.

**Comment by wrwg** [comment]
Please open all bugs on inline functions in the aptos repo and attach the 'Move' project to them.
