### ISSUE TITLE
[Bug]VS Code extension does not work 

### ISSUE THREAD

**Issue by Unberant** [move-language/move#998]
# 🐛 Bug

installed using cargo install move-cli & move-analyser
also installed aptos-cli but I don't think it has any effect 
```sh
cargo install --git https://github.com/move-language/move move-cli --branch main
cargo install --git https://github.com/diem/move move-analyzer  --features "address32"
```
Installed the move-analyzer extension in VS Code

But when I work with .move files I can't: compiler diagnostics, move to definition, move to type definition, move to references, type on hover, outline view, etc. 

I also tried changing the 'move-analyzer.server.path' to "~/.cargo/bin/move-analyzer" That didn't work

## Error message

In the 'OUTPUT' section of the VS Code console, if you select Move Language Server
will show the following output 
```
Starting language server '/home/user/.cargo/bin/move-analyzer' communicating via stdio...
starting symbolicator runner loop
symbolicating "Project_path/aptos-core/aptos-move/move-examples/hello_blockchain"
typed AST compilation failed    <--- I think this is the main problem
text document notification
scheduling run for "Project_path/aptos-core/aptos-move/move-examples/hello_blockchain/sources/hello_blockchain.move"
scheduled run
text document notification handled
symbolication started
```

Move Analyzer CIient:
```
INFO [3/21/2023, 6:13:05 PM]: move.move-analyzer version 0.0.10
INFO [3/21/2023, 6:13:05 PM]: configuration: {"server":{"path":"~/.cargo/bin/move-analyzer"}, "trace":{"server": "verbose"}}
INFO [3/21/2023, 6:13:05 PM]: Starting client...
```

## System information

**Please complete the following information:**
- wsl : Ubuntu 2022
- rustc 1.65.0
- active toolchain: 1.65.0-x86_64-unknown-linux-gnu
- move-cli 0.1.0
- move-analyzer 1.0.0

**Comment by dmshvetsov** [comment]
@Unberant hey, did you resolve the issue? Did you find what caused "typed AST compilation failed" error?
